  steps:
  mtaBuild:
    buildTarget: 'CF'
  steps:     
    cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF_Credential'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'd074337trial'
      space: 'dev'
  steps:
    tmsUpload:
      credentialsId: TMS_Credential
      nodeName: ProdCD
      mtaPath: /var/jenkins_home/workspace/livery_transport-service-develop/ci_test_project.mtar   
  stages:
    Release:
      tmsUpload: true