 
  steps:
  mtaBuild:
    buildTarget: 'CF'
  steps:
  steps:
  tmsUpload:
    credentialsId: CF_Credential
    nodeName: DevCD
    mtaPath: /var/jenkins_home/workspace/ContinousDelivery_Develop@2/ci_test_project.mtar
      cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF_Credential'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'd074337trial'
      space: 'dev'
